name: educazy
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"

dependencies:
  alan_voice: ^3.6.0
  animated_splash_screen: ^1.3.0
  badges: ^2.0.3
  camera: ^0.10.0+1
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  file_picker: ^4.6.1
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  flutter:
    sdk: flutter
  flutter_background: ^1.1.0
  flutter_inappwebview: ^5.4.3+7
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_svg: ^1.1.4
  flutter_tts: ^3.5.1
  flutter_vector_icons: ^1.0.0
  google_fonts: ^3.0.1
  highlight_text: ^1.4.1
  logger: ^1.1.0
  multi_select_flutter: ^4.1.2
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  permission_handler: ^10.0.0
  provider: ^6.0.3
  read_pdf_text: ^0.2.1
  shared_preferences: ^2.0.15
  speech_to_text: ^5.6.1
  string_similarity: ^2.0.0
  tflite: ^1.1.2
  url_launcher: ^6.1.5
  pdf: ^3.8.3
  open_file: ^3.2.1
  syncfusion_flutter_pdfviewer: ^20.2.45-beta

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/
